# Generated by Django 3.2.7 on 2021-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('monthly_sub', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('max_signups', models.IntegerField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('plan_features', models.JSONField()),
            ],
        ),
    ]
