# Generated by Django 3.2.7 on 2021-09-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupPlans',
        ),
    ]
