# Generated by Django 3.2.7 on 2021-10-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
