# Generated by Django 3.2.7 on 2021-10-16 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='allergen_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_since',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='kitchen_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='service_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='sms_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='sms_transactional',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
