# Generated by Django 3.2.7 on 2021-10-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20211016_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='allergen_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Allergen & Intollerances Notes'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_since',
            field=models.DateField(auto_now_add=True, verbose_name='Guest Since'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='kitchen_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Kitchen Notes'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Guest Rating'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='service_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Service Notes'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='sms_marketing',
            field=models.BooleanField(default=False, verbose_name='SMS Marketing Consent'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='sms_transactional',
            field=models.BooleanField(default=True, verbose_name='SMS Transactional Consent'),
        ),
    ]
