# Generated by Django 3.2.7 on 2021-10-31 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Guest Rating'),
        ),
    ]
