# Generated by Django 3.2.7 on 2021-09-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateField()),
                ('people', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('guest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guests.guest')),
            ],
        ),
    ]
