# Generated by Django 3.2.7 on 2021-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20211017_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.IntegerField(default=2, verbose_name='People'),
        ),
    ]
