# Generated by Django 3.2.7 on 2021-10-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('CON', 'Confirmed'), ('CAN', 'Cancelled'), ('DEN', 'Denied'), ('NOS', 'No-Show'), ('REQ', 'Requested'), ('SEA', 'Seated'), ('TAB', 'Table Ready'), ('WAI', 'Waitlist')], default='REQ', max_length=3),
        ),
    ]
