# Generated by Django 3.2.7 on 2021-10-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20211021_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
